### ISSUE TITLE
v0.3.0 physics based transitions don't end at specified value

### ISSUE THREAD

**Issue by MajorBreakfast** [Famous/famous#367]
``` JavaScript
this.transitionable.set(
  1,
  { method: 'snap', period: 300 },
  function() { console.log(this.transitionable.get()) }.bind(this)
)
```
Output: `1.0083897947331086 ` instead of `1`

**Comment by bmatto** [comment]
I'm seeing this behavior with a TransitionableTransform, and visually it's a bit jarring - I see @AdamCmiel note about setting the desired value in the callback - but it doesn't help the issue visually.

I have something like this -

```javascript
    var spring = {
      method: 'spring',
      period: 500,
      dampingRatio: 0.45
    };

    this.mainTransform.setRotate([Math.PI * 0.5, 0, 0], spring);
    this.mainTransform.setTranslate(translateXYZ, spring);
    this.mainTransform.setScale([1.3,1.3,1.3], spring);
```

Results can be seen here http://fullstack-nh.com/ just click/tap on one of the pizza boxes.  Is there something I can do to mitigate the jump at the end of the transition?

**Comment by StephanBijzitter** [comment]
@bmatto, it's a bit (okay... a huge) of a hack, but consider the following:
(completely untested and written in in this comment box)

```javascript
var target = surface._target;
target.style.transition = 'width 0.0s, height 0.0s';

setSize([width, height], animation, function(surface, target) {
	target.style.transition = 'width 0.4s, height 0.4s';
	surface.setSize([width, height]);
}.bind(window, surface, target));
```

**Comment by bmatto** [comment]
The idea here being to use a css transition inline to help "land" the tween ... i'll see how it looks.

Am I correct in assuming that jump will be fixed with this issue, or is that something different?

**Comment by StephanBijzitter** [comment]
@bmatto well it depends what is causing the jump really, but for anything that can be transitioned with css it should make it a lot smoother at the end.

On a sidenote though, I see you're scaling from 1 to 1.3, which seems alright, but I'd go the other way round.

Say for example that a pizza box is 100 by 100 pixels (at normal scale), you'd scale up to simulate 130 by 130 pixels, but are obviously missing 90 pixels worth of data that way.

Now let's do something else, what if we pretend the size at normal scale is not 100, but 130 and the initial state is simply scaled down. (which would result in super sampling, giving as much detail as it otherwise would).

initial size would be 130 by 130 with a scale of 0.8 (resulting in a visible 104 by 104 pizza box) and when clicked you'd set the scale to 1.0 (resulting in 130 by 130).

Scaling down is (almost) always better than up! :+1:

**Comment by bmatto** [comment]
@StephanBijzitter Thanks for note about scaling - that's very helpful indeed. :+1:

**Comment by MylesBorins** [comment]
I'm going to close this issue for now.  Please feel free to reopen it.
