### ISSUE TITLE
Mixed Mode and Existing API (Comments)

### ISSUE THREAD

**Issue by jd-carroll** [Famous/famous#521]
A Note on Mixed Mode:  **I would rather you completely break my existing app with the new API than sacrifice performance to support backwards compatibility.**

While reading #111  this came to mind and I thought I would create a separate topic because I'm certain there will be any number of differing opinions on this.  From what I have been able to gather on the new mixed mode, backwards compatibility may not even be an option.

My 2 cents

**Comment by AdrianRossouw** [comment]
so basically the render tree should be a virtual dom?

**Comment by TDSFugal** [comment]
The doThatFrom pattern is very useful.  I hope it stay for two reasons:

1) No way to adjust the spatial trajectory of the transition using the original  set(endState, transition, callback) pattern.  The transition object only allows temporal control (duration and "curve"), but the path from start to finish is implicit and cannot be changed.  For a one-D property like opacity that is not a big issue since there is only one possible path, but most properties are two or three dimensional with an infinite number of trajectories from start to finish. doThatFrom accepts a function as an argument, so there is the possibility of writing code to generate any of the possible trajectories.  There is no loss in generality because doThatFrom also accepts Transition objects so the simplicity of "set(endState, transition, callback)" with its implicit trajectory is still there.

2) Easy to synchronous multiple animations. Perhaps I'm missing something, but when I need four things to happen simultaneously it's easier to provide four functions that do exactly what I want than having four sets of controls to adjust.  Until doThatFrom came along I was spending way too much time rooting about in the Famo.us source code trying to figure out what the built-in functionality was going to do, and then engineering a controller for the controls to get it to do what I wanted it to do. 

As for performance, when an animation finishes a second call to ThatFrom with a constant end-state value clears the getter and stops the recalculations.  Yes, it's an extra line of code, but the extra typing is easy and does the job. 

@Michael - Roger on your point that the rest of the platform uses the Set pattern almost exclusively (Draggables, for example, don't have a translateFrom method).  Moving away from the set transition pattern would be painful, but staying with it after depreciating it in Modifier would be painful too.  I have a few ideas that are working for me and might help if you are interested. 

Double thumbs-up for both "get it right for 1.0" and Stephen's point about telegraphing the changes to the developer community WELL in advance. It would be such a nice kindness.

**Comment by MylesBorins** [comment]
MIXED MODE IS HERE

http://github.com/famous/engine
