### ISSUE TITLE
HELP/QUESTION: Famo.us + ES6 (with Traceur)

### ISSUE THREAD

**Issue by thebigredgeek** [Famous/famous#563]
Hey Guys,

I was wondering if there were any clear examples on how to use Famo.us with ES6 (compiled with Traceur) for the browser.  If not, can someone provide a simple example on how to do this?  It seems like a natural progression for Famo.us given the Object Oriented nature of the framework.

Thanks!

**Comment by alexanderGugel** [comment]
Should be possible. The easiest way to get started would probably be to use the [browserify-seed](https://github.com/Famous/browserify-seed) and add [es6ify](https://github.com/thlorenz/es6ify) as a transform. Unfortunately, it seems like defining transforms in the `package.json` or as command line options is currently not supported in es6ify (see https://github.com/thlorenz/es6ify/pull/65).

That's the reason why you would have to write a custom build script for that. Something like that:

`build.js`

```javascript
var fs = require('fs');
var famousify = require('famousify');
var es6ify = require('es6ify');
var cssify = require('cssify');
var brfs = require('brfs');
var browserify = require('browserify');

browserify({ debug: true })
    .add(es6ify.runtime)
    .transform(es6ify)
    .transform(famousify)
    .transform(cssify)
    .transform(brfs)
    .require(require.resolve('./src/index.js'), { entry: true })
    .bundle()
    .pipe(fs.createWriteStream('./public/bundle.js'));
```

Same with watchify. Otherwise, you'll have to run `node build.js` every time you make a change.

I created a simple proof of concept and got it to the point where it's actually rendering something:

Inheriting from View via `extend` seems to work. Code is here: https://github.com/alexanderGugel/browserify-seed/tree/es6ify

I spent like 30 minutes on it, so bear with me, but should be a good proof of concept.

* Clone down `https://github.com/alexanderGugel/browserify-seed/tree/es6ify`
* `npm i && npm build`


Have fun!

**Comment by speigg** [comment]
Use webpack, I find it to be much more powerful (and performant) than browserify. Also, I've started using 6to5 instead of Traceur... 6to5 implements much more of the es6 spec and generates much cleaner code and simpler code.

**Comment by TheAlphaNerd** [comment]
You can toss es6to5ify as a transform in the browserify seed

**Comment by alexanderGugel** [comment]
@TheAlphaNerd Seems like it's called [6to5ify](https://www.npmjs.com/package/6to5ify), not [es6to5ify](https://www.npmjs.com/package/es6to5ify).

**Comment by TheAlphaNerd** [comment]
Woops.  Good catch

**Comment by thebigredgeek** [comment]
I was actually hoping to be able to use the [JSPM](http://jspm.io/) toolchain (which includes ES6, loader, and Traceur tooling) since this appears to be the direction of the industry (away from RequireJS/Browserify and Bower/JamJS/NPM for frontend assets)  Any ideas?  This seems to be the next-gen best practice and I think it would make sense for Famo.us to align with this.

**Comment by TheAlphaNerd** [comment]
There is no reason you can't just use es6 and import things as you would like.  We are starting to experiment internally, expect an es6 seed in the very near future.

I'm closing this issue for right now. Feel free to reopen if you have more questions

**Comment by thebigredgeek** [comment]
MTW @TheAlphaNerd , we'd still like to reschedule that visit.  This is Andrew from Jiff :)
