### ISSUE TITLE
Scrollview using lots of memory

### ISSUE THREAD

**Issue by continuata** [Famous/famous#611]
I've got 2 Scrollviews (using Famous/Angular)

![screen shot 2015-01-31 at 00 26 27](https://cloud.githubusercontent.com/assets/1593397/5986099/18e8cc1c-a8e6-11e4-929f-49b76df64b81.png)

Looking at Chrome Inspector's timeline I'm getting a sawtooth JS Heap memory allocation, presumably due to all the "Animation Frame Fired" events (in Famous global) accumulating and then garbage collection cleaning some of it periodically.
The result is a Heap that uses 136MB at peak and 121MB at lowest, and I'm not even moving anything in the view.

![screen shot 2015-01-31 at 01 05 31](https://cloud.githubusercontent.com/assets/1593397/5986102/24a5fdea-a8e6-11e4-89d4-42aa165605a7.png)

Is this to be expected in Famous?
It looks like the render loop is being called all the time irrespective of events, which I'm assuming is at the core of how Famous works, I'm not noticing any performance hit in terms of usability, but the memory usage is concerning. 130MB peaks seems like a lot for a simple web-app.

**Comment by michaelobriena** [comment]
Famo.us currently makes a ton of memory every frame because of the spec we use to construct our 3D transform tree.  We are working on a more optimized version that should drastically cut down the per frame memory usage.

For the time being, I would try shrinking the margins on your scrollview so that you stop calculating the transforms for stuff that is incredibly far away from the viewport.

**Comment by continuata** [comment]
actually looks like it isn't famous at all ... I replaced the Scrollview with an ng-repeat of divs inside one surface instead and it still used the same memory. Naughty Angular!

**Comment by solomon-gumball** [comment]
Naughty naughty!
