### ISSUE TITLE
ScrollView bit laggy on Android

### ISSUE THREAD

**Issue by BodhiHu** [Famous/famous#669]
Hi guys, I found ScrollView is bit laggy on the Android device(try to repeatedly scroll with your finger very quickly), though the scrolling is really smooth on the iPad and Macbook.

I tested this on my Nexus 4 with Android 5.0 and Chrome 41.0.2272.96.

**Comment by Carlosriverae** [comment]
That's mostly due to the limitations of Chrome. I'd recommend building w/ Crosswalk ( crosswalk-project.org )

**Comment by BodhiHu** [comment]
Hi @Carlosriverae , can you give more details on those limitations?

**Comment by Carlosriverae** [comment]
Yeah sure, Android usually forces apps to use its own webview which is usually an old outdated browser. The nexus line has its own, galazy phones have their own etc, so consistency is not really there. However building with crosswalk lets you package a brand new browser into your app so that even old android phones use a newer version of chrome to display your app. This increases performance as well. You can test our our app ( requestedapp.com ), download it and play with the scrollview. It's definably not 100% smooth like our iOS app counterpart, but compared to when we did not use crosswalk, this version is a ton better! 
- Source: Our android app is build on crosswalk/famo.us

**Comment by BodhiHu** [comment]
Oh, gee, from their site this is really promising, I will definitely try crosswalk, many thanks for your help : )

Also I'm closing this issue, as crosswalk seems to be the solution.
